import type { Purchase, PurchasePayload } from '@/types/purchase'
import type { PurchaseFormInput, PurchaseFormValues } from './schema'

export function emptyPurchaseValues(): PurchaseFormInput {
  return {
    branch_id: '',
    warehouse_id: '',
    supplier_id: '',
    supplier_invoice_no: null,
    status: 'draft',
    purchase_date: new Date().toISOString().slice(0, 10),
    expected_date: null,
    discount_type: null,
    discount_amount: 0,
    tax_scope: 'line',
    tax_rate_id: null,
    tax_rate_type: null,
    tax_rate: 0,
    tax_type: null,
    shipping_charges: 0,
    notes: null,
    staff_note: null,
    items: [],
  }
}

export function valuesFromPurchase(purchase: Purchase): PurchaseFormInput {
  return {
    branch_id: purchase.branch_id,
    warehouse_id: purchase.warehouse_id,
    supplier_id: purchase.supplier_id,
    supplier_invoice_no: purchase.supplier_invoice_no,
    status: purchase.status === 'draft' ? 'draft' : 'confirmed',
    purchase_date: purchase.purchase_date,
    expected_date: purchase.expected_date,
    discount_type: purchase.discount_type as 'fixed' | 'percentage' | null,
    discount_amount: Number(purchase.discount_amount) || 0,
    tax_scope: (purchase.tax_scope as 'line' | 'sale') ?? 'line',
    tax_rate_id: purchase.tax_rate_id ?? null,
    tax_rate_type: purchase.tax_rate_type ?? null,
    tax_rate: Number(purchase.tax_rate) || 0,
    tax_type: purchase.tax_type ?? null,
    shipping_charges: Number(purchase.shipping_charges) || 0,
    notes: purchase.notes,
    staff_note: purchase.staff_note,
    items: purchase.items.map((item) => ({
      product_id: item.product_id,
      variation_id: item.variation_id,
      product_label: [item.product?.name, item.variation?.name].filter(Boolean).join(' / ') || item.product_id,
      sku: item.variation?.sku ?? item.product?.sku ?? null,
      unit_id: item.product?.unit?.id ?? null,
      unit_name: item.product?.unit?.short_name ?? item.product?.unit?.name ?? null,
      sub_unit_id: item.sub_unit_id ?? null,
      unit_label: item.unit_label ?? null,
      has_sub_unit: !!item.sub_unit,
      _default_sub_unit_id: item.sub_unit_id ?? null,
      conversion_factor: item.sub_unit?.conversion_factor ?? null,
      stock_tracking: item.product?.stock_tracking ?? 'none',
      received_quantity: Number(item.received_quantity) || 0,
      quantity: Number(item.quantity),
      unit_cost: Number(item.unit_cost),
      discount_type: item.discount_type as 'fixed' | 'percentage' | null,
      discount_amount: Number(item.discount_amount) || 0,
      tax_rate_id: item.tax_rate_id ?? null,
      tax_rate_type: item.tax_rate_info?.type ?? null,
      tax_rate: Number(item.tax_rate) || 0,
      tax_type: item.tax_rate_info?.type === 'fixed' ? 'exclusive' : null,
      notes: item.notes,
    })) as PurchaseFormInput['items'],
  }
}

export function buildPurchasePayload(values: PurchaseFormValues): PurchasePayload {
  return {
    branch_id: values.branch_id,
    warehouse_id: values.warehouse_id,
    supplier_id: values.supplier_id,
    supplier_invoice_no: values.supplier_invoice_no || null,
    status: values.status,
    purchase_date: values.purchase_date,
    expected_date: values.expected_date || null,
    discount_type: values.discount_type || null,
    discount_amount: values.discount_amount || null,
    tax_scope: values.tax_scope ?? 'line',
    tax_rate_id: values.tax_rate_id || null,
    tax_rate_type: values.tax_rate_type || null,
    tax_rate: values.tax_rate || null,
    tax_type: values.tax_type || null,
    shipping_charges: values.shipping_charges || null,
    notes: values.notes || null,
    staff_note: values.staff_note || null,
    items: values.items.map((item: PurchaseFormValues['items'][number]) => ({
      product_id: item.product_id,
      variation_id: item.variation_id || null,
      sub_unit_id: item.sub_unit_id || null,
      quantity: item.quantity,
      unit_cost: item.unit_cost,
      discount_type: item.discount_type || null,
      discount_amount: item.discount_amount || null,
      tax_rate_id: item.tax_rate_id || null,
      tax_rate: item.tax_rate || null,
      notes: item.notes || null,
    })),
  }
}
