<?php

namespace App\Exports;

class ProductTemplateExport extends AbstractProductTemplateExport
{
    public function headings(): array
    {
        return [
            'name',
            'type',
            'sku',
            'barcode_type',
            'unit',
            'sub_unit',
            'category',
            'brand',
            'tax_rate',
            'price_group',
            'rack_location',
            'description',
            'stock_tracking',
            'has_expiry',
            'tax_type',
            'track_inventory',
            'is_for_selling',
            'is_active',
            'selling_price',
            'purchase_price',
            'sub_unit_selling_price',
            'sub_unit_purchase_price',
            'alert_quantity',
            'max_stock_level',
            'minimum_selling_price',
            'profit_margin',
            'weight',
            'combo_items',
            'custom_fields',
        ];
    }

    protected function sampleRows(): array
    {
        return [
            [
                'name' => 'Sample Product',
                'type' => 'single',
                'sku' => 'SMP-001',
                'barcode_type' => 'C128',
                'unit' => 'pcs',
                'sub_unit' => 'box',
                'category' => 'Sample Category',
                'brand' => 'Sample Brand',
                'tax_rate' => 'VAT 10%',
                'price_group' => 'Retail',
                'rack_location' => 'RK-001',
                'description' => 'Optional description',
                'stock_tracking' => 'none',
                'has_expiry' => 'no',
                'tax_type' => 'exclusive',
                'track_inventory' => 'yes',
                'is_for_selling' => 'yes',
                'is_active' => 'yes',
                'selling_price' => '10.00',
                'purchase_price' => '5.00',
                'sub_unit_selling_price' => '9.50',
                'sub_unit_purchase_price' => '4.50',
                'alert_quantity' => '10',
                'max_stock_level' => '100',
                'minimum_selling_price' => '8.00',
                'profit_margin' => '20',
                'weight' => '0.250',
                'custom_fields' => '{"color":"Blue","size":"Medium"}',
            ],
            [
                'name' => 'Sample Service',
                'type' => 'service',
                'sku' => 'SRV-001',
                'barcode_type' => 'C128',
                'description' => 'Services do not require a unit or inventory tracking',
                'stock_tracking' => 'none',
                'has_expiry' => 'no',
                'tax_type' => 'exclusive',
                'track_inventory' => 'no',
                'is_for_selling' => 'yes',
                'is_active' => 'yes',
                'selling_price' => '25.00',
                'purchase_price' => '0.00',
                'custom_fields' => '{}',
            ],
            [
                'name' => 'Sample Combo Product',
                'type' => 'combo',
                'sku' => 'CMB-001',
                'barcode_type' => 'C128',
                'unit' => 'pcs',
                'category' => 'Sample Category',
                'brand' => 'Sample Brand',
                'description' => 'Import component products before the combo row',
                'stock_tracking' => 'none',
                'has_expiry' => 'no',
                'tax_type' => 'exclusive',
                'track_inventory' => 'no',
                'is_for_selling' => 'yes',
                'is_active' => 'yes',
                'selling_price' => '20.00',
                'purchase_price' => '10.00',
                'minimum_selling_price' => '18.00',
                'combo_items' => '[{"child_product":"SMP-001","quantity":2}]',
                'custom_fields' => '{}',
            ],
        ];
    }
}
